# Generated by Django 3.2 on 2021-06-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_status_listing_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cur_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
